name: "Cargo get version"
description: "Get version number from Cargo.toml"
inputs:
  cargoFilePath:
    description: "Path to where your Cargo.toml is"
    required: true
    default: "Cargo.toml"
outputs:
  version:
    description: "Version number"
runs:
  using: "node16"
  main: "dist/index.js"
